import ResultsTable from './ResultsTable'
import ResultsChart from './Charts'
import SummaryCard from './SummaryCard'

/**
 * Read-only results dashboard: status counts, extracted test table,
 * chart, bilingual summary sections, and food/lifestyle guidance cards.
 */
export default function ReportDashboard({ report }) {
  const rows = report.extracted_results || []
  const analysis = report.analysis

  const counts = rows.reduce(
    (acc, r) => {
      const key = (r.status || 'Unknown')
      acc[key] = (acc[key] || 0) + 1
      return acc
    },
    { Normal: 0, Low: 0, High: 0, Unknown: 0 }
  )

  return (
    <div className="dashboard-container">
      <div className="status-strip">
        <div className="status-pill">
          <span className="num">{rows.length}</span>
          Tests Found
        </div>
        <div className="status-pill status-pill-success">
          <span className="num">{counts.Normal}</span>
          Normal
        </div>
        <div className="status-pill status-pill-info">
          <span className="num">{counts.Low}</span>
          Low
        </div>
        <div className="status-pill status-pill-warning">
          <span className="num">{counts.High}</span>
          High
        </div>
      </div>

      <div className="card">
        <div className="card-header-flex">
          <div>
            <h2>Extracted Test Results</h2>
            <p className="card-subtext">Values read directly from report image/PDF via OCR</p>
          </div>
        </div>
        <ResultsTable rows={rows} editable={false} />
      </div>

      <div className="card">
        <h2>Values vs. Reference Range</h2>
        <ResultsChart rows={rows} />
      </div>

      {analysis && (
        <div className="analysis-section">
          <h2 className="section-title-md">Bilingual AI Explanations & Guidance</h2>
          
          <SummaryCard
            title="Overall Summary"
            icon="📋"
            englishText={analysis.overall_summary_en}
            tamilText={analysis.overall_summary_ta}
          />
          <SummaryCard
            title="Abnormal Findings"
            icon="⚠️"
            highlight={counts.High > 0 || counts.Low > 0}
            englishText={analysis.abnormal_findings_en}
            tamilText={analysis.abnormal_findings_ta}
          />
          <SummaryCard
            title="Normal Findings"
            icon="✅"
            englishText={analysis.normal_findings_en}
            tamilText={analysis.normal_findings_ta}
          />
          <SummaryCard
            title="Worth Discussing With Your Doctor"
            icon="🩺"
            englishText={analysis.attention_points_en}
            tamilText={analysis.attention_points_ta}
          />

          <div className="education-grid">
            <SummaryCard
              title="Food & Lifestyle Education"
              icon="🥗"
              accentColor="purple"
              englishText={analysis.lifestyle_en || "Focus on balanced nutrition, adequate hydration (2-3L daily), and regular moderate exercise."}
              tamilText={analysis.lifestyle_ta || "கீரைகள், காய்கறிகள் மற்றும் சத்தான உணவுகளை உட்கொள்ளுங்கள். போதிய தண்ணீர் குடித்து உடற்பயிற்சி செய்யுங்கள்."}
            />

            <SummaryCard
              title="Self-Care & Prevention Tips"
              icon="💡"
              accentColor="lavender"
              englishText={analysis.prevention_en || "Schedule regular health monitoring, prioritize 7-8 hours of sleep, and bring written questions to your next physician visit."}
              tamilText={analysis.prevention_ta || "ஆண்டுதோறும் உடல் பரிசோதனை செய்யுங்கள், 7-8 மணிநேரம் தூங்குங்கள், மருத்துவரிடம் கேட்க வேண்டிய கேள்விகளை குறித்து வைத்துக்கொள்ளுங்கள்."}
            />
          </div>

          {analysis.ai_provider && (
            <p className="ai-metadata-note">
              Summary generated by {analysis.ai_provider} ({analysis.ai_model})
            </p>
          )}
        </div>
      )}
    </div>
  )
}
